all:
	javac-algs4 PrimMST.java
	javac-algs4 EagerPrimMST.java
	javac-algs4 KruskalMST.java
	javac-algs4 TestClient.java
	java-algs4 TestClient 10000EWG.txt

exercises:
	javac-algs4 Exercise439.java
	javac-algs4 Exercise4310.java
	java-algs4 Exercise439 tinyEWG.txt
	java-algs4 Exercise4310 tinyEWG.txt

clean:
	rm -rf *.class
